project/apps/Historia/urls.py
from django.urls import path
from .views import home

app_name = "Historia"

urlpatterns = [
    path("", home, name="home"),

]

project/apps/Home/urls.py
from django.urls import path
from .views import home

app_name = "Home"

urlpatterns = [
    path("", home, name="home"),

]

project/apps/Juegos/urls.py
from django.urls import path
from .views import home

app_name = "Juegos"

urlpatterns = [
    path("", home, name="home"),

]

project/apps/Libreria/urls.py
from django.urls import path
from .views import home

app_name = "Libreria"

urlpatterns = [
    path("", home, name="home"),

]

project/apps/Lugares/urls.py
from django.urls import path
from .views import home

app_name = "Lugares"

urlpatterns = [
    path("", home, name="home"),

]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
        path("", include("Home.urls")),
    path("historia/", include("Historia.urls")),
    path("juegos/", include("Juegos.urls")),
    path("libreria/", include("Libreria.urls")),
    path("lugares/", include("Lugares.urls")),
    path("subscribete/", include("Subscripcion.urls")),
    path("series_peliculas/", include("series_peliculas.urls")),

]

project/apps/Home/models.py
from django.db import models

# Create your models here.

project/apps/Home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, "Home/index_home.html")

project/apps/Home/templates/Home/base_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Rincón Star Wars</title>
        <link rel="icon" type="image/x-icon" href="{% static 'Home/assets/favicon.ico' %}" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'Home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Header and Navegation bar -->
        {% include 'Home/navbar.html' %}

        {% block CONTENIDO %}
        {% endblock CONTENIDO %}

        {% include 'Home/footer.html' %}

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'Home/js/scripts.js' %}"></script>
    </body>
</html>

project/apps/Home/templates/Home/card_photo.html
{% load static %}
<section class="page-section clearfix">
    <div class="container">
        <div class="intro">
            <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'Home/assets/img/han_solo.jpg' %}" alt="..." />
            <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                <h2 class="section-heading mb-4">
                    <span class="section-heading-upper">¿Qué esperas?</span>
                    <span class="section-heading-lower">¡Subscríbete ya!</span>
                </h2>
                <p class="mb-3">¡No dejes de informarte de este universo y mantente al día con las novedades que podemos brindarte!</p>
                <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="#!">¡Subscríbete!</a></div>
            </div>
        </div>
    </div>
</section>

project/apps/Home/templates/Home/footer.html
<footer class="footer text-faded text-center py-5">
    <div class="container"><p class="m-0 small">Copyright &copy; Your Website 2023</p></div>
</footer>

project/apps/Home/templates/Home/index_home.html
{% extends 'Home/base_home.html' %}

{% block CONTENIDO %}

{% include 'Home/promise.html' %}

{% include 'Home/card_photo.html' %}
    
{% endblock CONTENIDO %}

project/apps/Home/templates/Home/navbar.html
<header>
    <h1 class="site-heading text-center text-faded d-none d-lg-block">
        <span class="site-heading-upper text-primary mb-3">Encuentra todo lo que necesitas saber en</span>
        <span class="site-heading-lower">¡Rincón Star Wars!</span>
    </h1>
</header>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
        <a class="navbar-brand text-uppercase fw-bold d-lg-none" href="index.html">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'Home:home' %}">Home</a></li>
                <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'Historia:home' %}">Historias del Universo</a></li>
                <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'series_peliculas:home' %}">Series y Películas</a></li>
                <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'Juegos:home' %}">Juegos</a></li>
                <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'Libreria:home' %}">Librería</a></li>
                <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'Lugares:home' %}">Lugares Temáticos</a></li>
                <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'Subscripcion:home' %}">¡Subscríbete!</a></li>
            </ul>
        </div>
    </div>
</nav>

project/apps/Home/templates/Home/promise.html
<section class="page-section cta">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <div class="cta-inner bg-faded text-center rounded">
                    <h2 class="section-heading mb-4">
                        <span class="section-heading-upper">Nuestro</span>
                        <span class="section-heading-lower">Compromiso</span>
                    </h2>
                    <p class="mb-0">En nuestra página nos comprometemos a mantenerte informado acerca del universo de Star Wars para que puedas seguir disfrutando de este maravilloso mundo que generó LucasFilm. Aquí podrás enterarte de las historias de personajes, juegos asociados a la franquicia, cómics y libros para ampliar tus horizontes y lugares temáticos para que puedas disfrutar con amigos o en familia.</p>
                </div>
            </div>
        </div>
    </div>
</section>